### ISSUE TITLE
wgpu failed on Mac m1

### ISSUE THREAD

**Issue by Alphapage** [aakamenov/microui-rs#1]
Hello,

I tried to run demo example using wgpu, but it fails because of a memory error.
Is it working on linux or windows ?

Thank you in advance for your answer.

**Comment by aakamenov** [comment]
The wgpu renderer is currently not working and on hold, but I might get back to it at some point. I had issues with text rendering and seems like [wgpu-glyph](https://crates.io/crates/wgpu_glyph) can't be used to draw text in the same render pass as quads anyways. Or at least I couldn't figure out how... You'll have to use the femtovg renderer or write your own. Though it should just panic with unimplemented: https://github.com/aakamenov/microui-rs/blob/master/microui-wgpu/src/renderer.rs#L268

**Comment by Alphapage** [comment]
Ok my mistake!
But I hope you will find a way to implement wgpu quickly to support Vulkan or Metal.
femtovg should surpass macroquad for example with such a backend.
